### PR TITLE
Removal of deprecated operating systems

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by tersmitten** [comment]
@chn42 Thanks for you contribution. The only sad thing is that the role fails on Ubuntu 16.04 :-(

```
TASK: [../../ | install | dependencies] *************************************** 
<127.0.0.1> REMOTE_MODULE apt name=percona-server-client-5.5,percona-server-server-5.5,python-mysqldb state=latest
failed: [ubuntu-1604] => (item=percona-server-client-5.5,percona-server-server-5.5,python-mysqldb) => {"failed": true, "item": "percona-server-client-5.5,percona-server-server-5.5,python-mysqldb"}
msg: No package matching 'percona-server-client-5.5' is available
```

**Comment by chn42** [comment]
Hi Mischa,

maybe it’s time for 5.6 then as a default?

kind regards
Christoph

**Comment by tersmitten** [comment]
I'm almost there :-) 

Also see #14

**Comment by chn42** [comment]
Additionally I’m not able to start vagrant boxes due to the NIC renaming since 15.10 wily, but this is another story.

**Comment by tersmitten** [comment]
That's an open `vagrant` ticket: https://github.com/mitchellh/vagrant/issues/7155

**Comment by chn42** [comment]
Yes I know, but just found out it’s related to the multi-vm network, which I guess is not really needed in this case. Will push a new PR with removed private_network shortly :-)

**Comment by tersmitten** [comment]
I like to keep the `private_network`

**Comment by chn42** [comment]
Don’t have a clue for what, but it’s your decision ;-)

Just noticed Percona haven’t released xenial packages so far, not just 5.5 :-(

**Comment by tersmitten** [comment]
Because I want to keep [all roles](https://github.com/Oefenweb?utf8=%E2%9C%93&query=ansible-) consistent.

https://www.percona.com/forums/questions-discussions/mysql-and-percona-server/percona-server-5-7/44197-eta-on-percona-server-packages-for-ubuntu-16-04-lts-xenial-xerus

**Pull request merged**
