### PR TITLE
Add support Percona Server 8.0.

### PR DESCRIPTION
**Pull request by MemberIT**
Add support Percona Server 8.0

### CODE REVIEW

**Comment by MemberIT** [comment]
Status of Travis CI is "in progress" but all tests "is passed" https://travis-ci.org/Oefenweb/ansible-percona-server/builds/478332557?utm_source=github_status&utm_medium=notification

**Comment by kieranajp** [comment]
I was wondering if this role supported 8.0, and found this PR :)

Is there any chance this will be supported / merged anytime soon? We've been using this role in production with 5.7 for a while and it would be awesome to use it with some newer 8.0 clusters.

Thanks :)

**Comment by Ases** [comment]
Is help needed to add Percona Server 8.0 or there is no intention to support this version?

These changes seem straightforward.

**Comment by tersmitten** [comment]
There's intention to support this version

**Comment by tersmitten** [comment]
Can you update the PR

**Comment by jstaf** [comment]
@tersmitten can you articulate what exactly remains to be done here? As far as I can tell, the changes work and everything looks good. It's just been waiting to be merged for 5 (!!!) years. Can you merge this?

**Comment by tersmitten** [comment]
@jstaf I looks like all the work has been done. I'll try to have a good look at it this week. Can you make sure that there're no conflicts in the (3) PR's?

**Pull request merged**
