### PR TITLE
Add support for Percona 5.7

### LINKED ISSUE #19: Add support for percona-server version 5.7

### PR DESCRIPTION
**Pull request by ewlarson**
Fixes #19

### CODE REVIEW

**Comment by tersmitten** [comment]
With what configuration did you run the playbook?

When I change the version to `5.7` and run `vagrant up` it get this:

```
TASK [../../ : ib logfile | start service] *************************************
task path: /home/mtersmitten/Documents/checkouts/Oefenweb/ansible-playbooks/roles/percona-server/tasks/ib-logfile.yml:38
fatal: [ubuntu-1204]: FAILED! => {"changed": false, "failed": true, "msg": "........................................................................................................................ * Percona Server 5.7.18-16 did not start. Please check logs for more details.\n"}
```

**Comment by ewlarson** [comment]
When I ran it successfully, I had also changed the default to 5.7 -- so maybe that's the reason it's not working for you?  If that is the difference, or regardless even, I think making 5.7 the default makes sense, as it's the latest stable build of Percona.

I ran it on Ubuntu 16.04.3 x64.  Does your error message here "[ubuntu-1204]" mean you were running it on Ubuntu 12.04?  Perhaps the 5.7 package just wasn't available to that build?

**Comment by tersmitten** [comment]
The Vagrantfile contains all supported operating systems (starting with 12.04) I'll check 16.04. 

But did you make any changes to buffer pool size or what so ever?

**Comment by ewlarson** [comment]
No, I made no other changes other then these.  Like I said before, it all seemed painfully small and silly for an actual PR.

**Comment by czerasz** [comment]
I can confirm that it works.

Tested on a DigitalOcean droplet.

System details (Debian 9.3 x64):

```bash
uname -a
Linux debian-s-4vcpu-8gb-fra1-01 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```

Here is my playbook:

```yaml
---

- name: Prepare Percona installation
  hosts: percona
  tasks:
    # Resource: https://blog.sleeplessbeastie.eu/2017/11/02/how-to-fix-missing-dirmngr/
    - name: Install dirmngr to make apt-key work
      apt:
        name: dirmngr
        state: installed
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes

- name: Install Percona (MySQL variant)
  hosts: percona
  roles:
    - role: tersmitten.percona-server
  vars:
    percona_server_version: 5.7
    percona_server_root_password: 'secret'

    percona_server_etc_my_cnf:
      - section: mysqld
        options:
          # Don't expose MySQL port to the public
          - name: bind_address
            value: localhost

    percona_server_databases_present:
      - name: test_db

    percona_server_users_present_hosts:
      - localhost

    percona_server_users_present:
      - name: user1
        password: 'secret'
        privs:
          - 'test_db.*:ALL'
        hosts:
          - localhost

      - name: user2
        password: 'secret'
        privs:
          - 'test_db.*:ALL'
        hosts:
          - localhost
````

Here is the result of running it:

```bash
$ ansible-playbook percona.yml
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this 
rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Prepare Percona installation] **************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************
ok: [test-db-01]

TASK [Install dirmngr to make apt-key work] ******************************************************************************************************************************
ok: [test-db-01]

PLAY [Install Percona (MySQL variant)] ***********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : version support | check] ***************************************************************************************************************
skipping: [test-db-01]

TASK [tersmitten.percona-server : first-run | check] *********************************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : repository | add public key] ***********************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : repository | add] **********************************************************************************************************************
ok: [test-db-01] => (item={u'url': u'http://repo.percona.com/apt stretch', u'type': u'deb', u'component': u'main'})
ok: [test-db-01] => (item={u'url': u'http://repo.percona.com/apt stretch', u'type': u'deb-src', u'component': u'main'})

TASK [tersmitten.percona-server : repository | apt-pin packages] *********************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : install | configure debconf] ***********************************************************************************************************
ok: [test-db-01] => (item={u'vtype': u'password', u'question': u'percona-server-server/root_password', u'name': u'percona-server-server-5.7', u'value': u'secret'})
ok: [test-db-01] => (item={u'vtype': u'password', u'question': u'percona-server-server/root_password_again', u'name': u'percona-server-server-5.7', u'value': u'secret'})

TASK [tersmitten.percona-server : install | dependencies] ****************************************************************************************************************
ok: [test-db-01] => (item=[u'percona-server-client-5.7', u'percona-server-server-5.7', u'python-mysqldb'])

TASK [tersmitten.percona-server : install | dependencies | check service] ************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : install | additional] ******************************************************************************************************************
changed: [test-db-01] => (item=[u'xtrabackup'])

TASK [tersmitten.percona-server : configure | copy certificate files] ****************************************************************************************************

TASK [tersmitten.percona-server : configure | update (global) configuration file] ****************************************************************************************
changed: [test-db-01]

TASK [tersmitten.percona-server : configure | update (root) configuration file] ******************************************************************************************
changed: [test-db-01]

TASK [tersmitten.percona-server : toolkit udfs | create (lock) directory] ************************************************************************************************
changed: [test-db-01]

TASK [tersmitten.percona-server : toolkit udfs | install] ****************************************************************************************************************
changed: [test-db-01] => (item={u'function': u'fnv1a_64', u'soname': u'libfnv1a_udf.so'})
changed: [test-db-01] => (item={u'function': u'fnv_64', u'soname': u'libfnv_udf.so'})
changed: [test-db-01] => (item={u'function': u'murmur_hash', u'soname': u'libmurmur_udf.so'})

TASK [tersmitten.percona-server : timezone info | create (lock) directory] ***********************************************************************************************
skipping: [test-db-01]

TASK [tersmitten.percona-server : timezone info | install] ***************************************************************************************************************
skipping: [test-db-01]

TASK [tersmitten.percona-server : databases | create] ********************************************************************************************************************
changed: [test-db-01] => (item={u'name': u'test_db'})

TASK [tersmitten.percona-server : databases | drop] **********************************************************************************************************************
ok: [test-db-01] => (item={u'name': u'test'})

TASK [tersmitten.percona-server : users | create (default hosts)] ********************************************************************************************************

TASK [tersmitten.percona-server : users | create (custom hosts)] *********************************************************************************************************
changed: [test-db-01] => (item=({u'password': u'secret', u'name': u'user1', u'privs': [u'test_db.*:ALL']}, u'localhost'))
changed: [test-db-01] => (item=({u'password': u'secret', u'name': u'user2', u'privs': [u'test_db.*:ALL']}, u'localhost'))

TASK [tersmitten.percona-server : users | drop (default hosts)] **********************************************************************************************************

TASK [tersmitten.percona-server : users | drop (custom hosts)] ***********************************************************************************************************

TASK [tersmitten.percona-server : plugins | create (lock) directory] *****************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : plugins | uninstall] *******************************************************************************************************************

TASK [tersmitten.percona-server : plugins | install] *********************************************************************************************************************

TASK [tersmitten.percona-server : queries | execute sql] *****************************************************************************************************************

TASK [tersmitten.percona-server : ib logfile | get datadir] **************************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : ib logfile | store datadir] ************************************************************************************************************
ok: [test-db-01]

TASK [tersmitten.percona-server : ib logfile | stop service] *************************************************************************************************************
skipping: [test-db-01]

TASK [tersmitten.percona-server : ib logfile | remove ib_logfile(s)] *****************************************************************************************************
skipping: [test-db-01] => (item=/var/lib/mysql/ib_logfile0) 
skipping: [test-db-01] => (item=/var/lib/mysql/ib_logfile1) 

TASK [tersmitten.percona-server : ib logfile | start service] ************************************************************************************************************
skipping: [test-db-01]

TASK [tersmitten.percona-server : start and enable service] **************************************************************************************************************
ok: [test-db-01]

RUNNING HANDLER [tersmitten.percona-server : restart percona-server] *****************************************************************************************************
changed: [test-db-01]

PLAY RECAP ***************************************************************************************************************************************************************
test-db-01                   : ok=23   changed=8    unreachable=0    failed=0 
```

PS:

I got issues when first installed `5.6` and then switched to `5.7`:

```bash

...

TASK [tersmitten.percona-server : databases | drop] **********************************************************************************************************************
ok: [test-db-01] => (item={u'name': u'test'})

TASK [tersmitten.percona-server : users | create (default hosts)] ********************************************************************************************************

TASK [tersmitten.percona-server : users | create (custom hosts)] *********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InterfaceError: (-1, 'error totally whack')
failed: [test-db-01] (item=({u'password': u'secret', u'name': u'user1', u'privs': [utest_db*:ALL']}, u'localhost')) => {"changed": false, "failed": true, "item": [{"name": "user1", "password": "secret", "privs": ["test_db.*:ALL"]}, "localhost"], "msg": "(-1, 'error totally whack')"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InterfaceError: (-1, 'error totally whack')
failed: [test-db-01] (item=({u'password': u'secret', u'name': u'user2', u'privs': [u'test_db.*:ALL']}, u'localhost')) => {"changed": false, "failed": true, "item": [{"name": "user2", "password": "secret", "privs": ["test_db.*:ALL"]}, "localhost"], "msg": "(-1, 'error totally whack')"}
 [WARNING]: Could not create retry file '/ansible/percona.retry'.         [Errno 30] Read-only file system: u'/ansible/percona.retry'
```

Please merge!

**Comment by tersmitten** [comment]
I'll try to have a look soon. In the mean time can you guys test all supported operating systems (in the `Vagrantfile`). I thought I had some issues with Ubuntu < 16.04 and maybe also older versions of Debian.

**Comment by tersmitten** [comment]
In Ubuntu 12.04 there's an issue with the `pid-file`. This causes the role not to work. Also I'm not sure what to do with the following files:

```
      - /etc/mysql/percona-server.conf.d/mysqld_safe.cnf
      - /etc/mysql/percona-server.conf.d/mysqld.cnf
      - /etc/mysql/percona-server.cnf
```

**Comment by tersmitten** [comment]
I think I figured everything out :-)

**Comment by tersmitten** [comment]
I tagged a new release guys

**Pull request closed without merging**
